### ISSUE TITLE
[newsmake] Latest release still has a problem with substrings.

### ISSUE THREAD

**Issue by AraHaan** [Elskom/Sdk#15]
## Issue Description

```
Unhandled Exception:
 
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Newsmake.Program.Formatline(String& input, Boolean tabs, Boolean output_format_md, Int32 line_length) in C:\projects\newsmake\Program.cs:line 46
   at Newsmake.Program.Main(String[] args) in C:\projects\newsmake\Program.cs:line 258
```
The error is pretty self explanatory that https://github.com/Elskom/newsmake/blob/7d8a09db60da4896061b9e705c80c963db9d0cc0/Program.cs#L46 has something wrong with the input length or the input position causing the input length to also fail.

# Debug information
- newsmake version: ``1.0.3``

## Fix suggestion

At this time I got no idea how I can fix this error causing the tool to crash.

**Comment by AraHaan** [comment]
ok, added you as a contributor. Also so this does not get repeated I added a test *.master file that generates a test changelog.
